/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PracticeDifficultyRouteImport } from './routes/practice/difficulty'
import { Route as PracticeResultsRouteImport } from './routes/practice/results'
import { Route as PracticeScenarioRouteImport } from './routes/practice/scenario'
import { Route as PracticeSessionRouteImport } from './routes/practice/session'
import { Route as PracticeSkillRouteImport } from './routes/practice/skill'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeDifficultyRoute = PracticeDifficultyRouteImport.update({
  id: '/practice/difficulty',
  path: '/practice/difficulty',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeResultsRoute = PracticeResultsRouteImport.update({
  id: '/practice/results',
  path: '/practice/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeScenarioRoute = PracticeScenarioRouteImport.update({
  id: '/practice/scenario',
  path: '/practice/scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeSessionRoute = PracticeSessionRouteImport.update({
  id: '/practice/session',
  path: '/practice/session',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeSkillRoute = PracticeSkillRouteImport.update({
  id: '/practice/skill',
  path: '/practice/skill',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/practice/difficulty': typeof PracticeDifficultyRoute
  '/practice/results': typeof PracticeResultsRoute
  '/practice/scenario': typeof PracticeScenarioRoute
  '/practice/session': typeof PracticeSessionRoute
  '/practice/skill': typeof PracticeSkillRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/practice/difficulty': typeof PracticeDifficultyRoute
  '/practice/results': typeof PracticeResultsRoute
  '/practice/scenario': typeof PracticeScenarioRoute
  '/practice/session': typeof PracticeSessionRoute
  '/practice/skill': typeof PracticeSkillRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/practice/difficulty': typeof PracticeDifficultyRoute
  '/practice/results': typeof PracticeResultsRoute
  '/practice/scenario': typeof PracticeScenarioRoute
  '/practice/session': typeof PracticeSessionRoute
  '/practice/skill': typeof PracticeSkillRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/progress'
    | '/settings'
    | '/practice/difficulty'
    | '/practice/results'
    | '/practice/scenario'
    | '/practice/session'
    | '/practice/skill'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/progress'
    | '/settings'
    | '/practice/difficulty'
    | '/practice/results'
    | '/practice/scenario'
    | '/practice/session'
    | '/practice/skill'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/progress'
    | '/settings'
    | '/practice/difficulty'
    | '/practice/results'
    | '/practice/scenario'
    | '/practice/session'
    | '/practice/skill'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  PracticeDifficultyRoute: typeof PracticeDifficultyRoute
  PracticeResultsRoute: typeof PracticeResultsRoute
  PracticeScenarioRoute: typeof PracticeScenarioRoute
  PracticeSessionRoute: typeof PracticeSessionRoute
  PracticeSkillRoute: typeof PracticeSkillRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/difficulty': {
      id: '/practice/difficulty'
      path: '/practice/difficulty'
      fullPath: '/practice/difficulty'
      preLoaderRoute: typeof PracticeDifficultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/results': {
      id: '/practice/results'
      path: '/practice/results'
      fullPath: '/practice/results'
      preLoaderRoute: typeof PracticeResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/scenario': {
      id: '/practice/scenario'
      path: '/practice/scenario'
      fullPath: '/practice/scenario'
      preLoaderRoute: typeof PracticeScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/session': {
      id: '/practice/session'
      path: '/practice/session'
      fullPath: '/practice/session'
      preLoaderRoute: typeof PracticeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/skill': {
      id: '/practice/skill'
      path: '/practice/skill'
      fullPath: '/practice/skill'
      preLoaderRoute: typeof PracticeSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  PracticeDifficultyRoute: PracticeDifficultyRoute,
  PracticeResultsRoute: PracticeResultsRoute,
  PracticeScenarioRoute: PracticeScenarioRoute,
  PracticeSessionRoute: PracticeSessionRoute,
  PracticeSkillRoute: PracticeSkillRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
